# v0.8

ESC = "\033["

# reset
RST = f"{ESC}0m"
RST_FG = f"{ESC}39m"
RST_BG = f"{ESC}49m"

RST_BOLD, RST_DIM, RST_ITALIC, RST_UNDER, RST_BLINK, RST_REVERSE, RST_HIDDEN, RST_STRIKE = [f"{ESC}{i}m" for i in range(21, 29)]

# txtStylin'
BOLD, DIM, ITALIC, UNDER, BLINK, RAPID_BLINK, REVERSE, HIDDEN, STRIKE = [f"{ESC}{i}m" for i in range(1, 10)]

# fgTXTcolors
BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE = [f"{ESC}{i}m" for i in range(30, 38)]

# brightFGcolors
BRIGHT_BLACK, BRIGHT_RED, BRIGHT_GREEN, BRIGHT_YELLOW, BRIGHT_BLUE, BRIGHT_MAGENTA, BRIGHT_CYAN, BRIGHT_WHITE = [f"{ESC}{i}m" for i in range(90, 98)]

# BGcolors
BG_BLACK, BG_RED, BG_GREEN, BG_YELLOW, BG_BLUE, BG_MAGENTA, BG_CYAN, BG_WHITE = [f"{ESC}{i}m" for i in range(40, 48)]

# brightBGcolors
BG_BRIGHT_BLACK, BG_BRIGHT_RED, BG_BRIGHT_GREEN, BG_BRIGHT_YELLOW, BG_BRIGHT_BLUE, BG_BRIGHT_MAGENTA, BG_BRIGHT_CYAN, BG_BRIGHT_WHITE = [f"{ESC}{i}m" for i in range(100, 108)]

"""
NO DOCSTRING HERE...
WAIT... OH FUCK...
I WAS HALF-WRONG!!!
"""
